project:
  type: website
  output-dir: docs
  resources:
    - google1b5dfd7c0d45a4a9.html
    - Dotun_Olaoye_CV.pdf

website:
  title: "Dotun Olaoye"
  site-url: "https://dotunolaoye.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: experience.qmd
        text: Experience
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/dotunolaoye
      - icon: envelope
        href: mailto:dsolaoye@missouri.edu

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    page-layout: article
