project:
  type: website
  output-dir: docs

website:
  title: "Dotun Olaoye"
  site-url: "https://dotunolaoye.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/dotunolaoye
      - icon: envelope
        href: mailto:dsolaoye@missouri.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
