---
title: "Publications"
---

Full list also available on [Google Scholar](https://scholar.google.com/citations?hl=en&user=KKN-ZewAAAAJ).

## Journal articles and preprints

**Olaoye, D.**, Bhattarai, G., Correll, J., Shi, A. Genetic analysis reveals novel genomic regions for downy mildew resistance and validates the potential for predictive breeding in spinach (*Spinacia oleracea*). Under review, *BMC Plant Biology*, 2026.

**Olaoye, D.**, Rasaki, L., Adesina, O., Kareem, B., Kandel, S., Ravelombola, W., Yang, Y., Shi, A. RNA-seq meta-analysis and machine learning identify stress-responsive genes and improve genomic prediction in common bean (*Phaseolus vulgaris* L.) with cross-species application in cowpea (*Vigna unguiculata* L.). *bioRxiv* (2026). [doi:10.64898/2026.08.08.743654](https://doi.org/10.64898/2026.08.08.743654) (preprint)

**Olaoye, D.**, Bhattarai, G., Feng, C. et al. Evaluation of downy mildew resistance in spinach (*Spinacia oleracea*). *Euphytica* 220, 38 (2024). [doi:10.1007/s10681-023-03289-9](https://doi.org/10.1007/s10681-023-03289-9)

Bhattarai G, **Olaoye D**, Mou B, Correll JC and Shi A (2022) Mapping and selection of downy mildew resistance in spinach cv. whale by low coverage whole genome sequencing. *Front. Plant Sci.* 13:1012923. [doi:10.3389/fpls.2022.1012923](https://doi.org/10.3389/fpls.2022.1012923)

Zia, B, A. Shi, **D. Olaoye**, H. Xiong, W. Ravelombola, P. Gepts, H.F. Schwartz, M.A. Brick, K. Otto, B. Ogg, and S, Chen. 2022. Genome-wide association study and genomic prediction for bacterial wilt resistance in common bean (*Phaseolus vulgaris*) core collection. *Front. Genet.* [doi:10.3389/fgene.2022.853114](https://doi.org/10.3389/fgene.2022.853114)

Ravelombola, W., Shi, A., Huynh, B.L., Qin, J., Xiong, H., Manley, A., Dong, L., **Olaoye, D.**, Bhattarai, G., Zia, B. and Alshaya, H., 2022. Genetic architecture of salt tolerance in a Multi-Parent Advanced Generation Inter-Cross (MAGIC) cowpea population. *BMC genomics*, 23(1), pp.1-22.

Ravelombola, W., Dong, L., Barickman, T.C., Xiong, H., **Olaoye, D.**, Bhattarai, G., Zia, B., Alshaya, H., Alatawi, I. and Shi, A., 2021. Evaluation of salt tolerance in cowpea at seedling stage. *Euphytica*, 217(6), pp.1-20.

Ravelombola, W., Shi, A., Chen, S., Xiong, H., Yang, Y., Cui, Q., **Olaoye, D.** and Mou, B., (2020). Evaluation of cowpea for drought tolerance at seedling stage. *Euphytica*, 216(8), pp.1-19.

Yang, Y., Shi, D., Wang, Y., Zhang, L., Chen, X., Yang, X. ... & Yang, G. (2020). Transcript profiling for regulation of sweet potato skin color in Sushu8 and its mutant Zhengshu20. *Plant Physiology and Biochemistry*, 148, 1-9.

## Conference presentations

Olaoye, D., Franklin, G., Schnabel, R., Thomas, J., Decker, J. Predicting Puberty and Fertility Traits in Multi-breed Beef Heifer Cattle. Poster, Population, Evolutionary, and Quantitative Genetics Conference (PEQG), 2026

Estimating genetic parameters and predicting puberty and fertility traits in multi-breed beef heifer cattle. Advances in Genome Biology and Technology (AGBT) Agricultural Meeting, 2025

Olaoye, D., Bhattarai, G., Feng, C., Correll, J. C., & Shi, A. (2020, August). Evaluation of Resistance to Pfs race 5 in Worldwide Spinach Collection. 2020 ASHS Annual Conference.

Olaoye, D., Shi, A., Ravelombola, W. S., Bhattarai, G., & Xiong, H. (2020, August). Drought Tolerance Characterization in two Contrasting Common Bean Genotypes. 2020 ASHS Annual Conference.

Olaoye, D., Bhattarai, G., Feng, C., Shi, A., & Correll, J. (2019, November). Evaluation of Incomplete Dominance in a Spinach Downy Mildew Resistance Locus. ASA, CSSA and SSSA International Annual Meetings.
